### ISSUE TITLE
IKE_AUTH Event not firing

### ISSUE THREAD

**Issue by antwacky** [corelight/zeek-spicy-ipsec#3]
Hi

I'm trying to capture the IP EAP identity during authentication. I did a packet capture whilst authenticating with the IPSEC server and can see the IKE_AUTH exchange in Wireshark, however the ikev2_auth_payload event is not firing.

I'd rather use the EAP event, but this isn't firing either.

My question, shouldn't the ikev2_auth_payload event be firing when I can see an IKE_AUTH exchange in the packet trace?

Thanks

**Comment by keithjjones** [comment]
Yes, I would expect the event to fire if you see it in the trace.  The logic is here for AUTH: https://github.com/corelight/zeek-spicy-ipsec/blob/master/analyzer/analyzer.spicy#L298 and here for EAP: https://github.com/corelight/zeek-spicy-ipsec/blob/master/analyzer/analyzer.spicy#L307  EAP is different than AUTH, depending on payload type value.  

Are you able to share the pcap?  There are so many options in IPSec that I couldn't get complete test coverage with the public pcaps I found.  If your pcap finds something broken, I'd like to fix it.  Thanks!

**Comment by keithjjones** [comment]
No problem at all!  I like getting bugs squashed if someone is nice enough to report them, and it's even nicer when there is a pcap.  Thanks!  I opened it in wireshark and saw this.  This is the exchange type with "IKE_AUTH" and not the payload type (https://github.com/corelight/zeek-spicy-ipsec/blob/master/analyzer/analyzer.spicy#L19 and https://github.com/corelight/zeek-spicy-ipsec/blob/master/analyzer/analyzer.spicy#L264).  The AUTH or EAP payload types do not exist in this pcap as far as I can tell.  What you are looking for may be in that encrypted data in your pcap.  That's why the events are probably not firing.  

![image](https://user-images.githubusercontent.com/5360855/153246254-c3a7f107-c16d-4ddb-b4b9-e5fb8ad4203e.png)

**Comment by pagey101** [comment]
Ah ok thanks, I did see a lot of IKE message events firing so assume those packets are IKE_MESSAGE types.

Here's what I'm trying to do. I want to associate the certificate common name (or EAP identity, both are the same) with a DNS request (over IPSEC).

My idea was to do something like the below... Capture the EAP authentication and stick it in a table against the virtual IP (this will get overwritten each time a new client assumes the given virtual IP). Then do a lookup in the table for each DNS request based on the source address.

As I mentioned, I can't get the events to fire unfortunately, I think you're saying this won't work because what I'm looking for is in an encrypted packet. Any ideas or am I stuck?

Apologies for the lengthy comment, any help is appreciated!

```
@load base/protocols/conn
@load base/protocols/dns
@load zeek-spicy-ipsec

global certTable: table[addr] of string = table();

module DNS;

export {
    redef record DNS::Info += {
        certificate: string &log &optional;
    };
}

hook DNS::set_session(c: connection, msg: dns_msg, is_query: bool) {
    if ( c$id$orig_h in certTable )
        c$dns$certificate = certTable[c$id$orig_h];
}

event IPSEC::ikev2_eap_payload(c: connection, is_orig: bool, msg: IPSEC::IKE_EAP_Msg) {
    #certTable[c$id$orig_h] = msg$message_id;
}

event IPSEC::ikev2_auth_payload(c: connection, is_orig: bool, msg: IPSEC::IKE_AUTH_Msg) {
    certTable[c$id$orig_h] = msg$auth_data;
}
```

**Comment by keithjjones** [comment]
For this to fire:

```
event IPSEC::ikev2_eap_payload(c: connection, is_orig: bool, msg: IPSEC::IKE_EAP_Msg) {
    #certTable[c$id$orig_h] = msg$message_id;
}

event IPSEC::ikev2_auth_payload(c: connection, is_orig: bool, msg: IPSEC::IKE_AUTH_Msg) {
    certTable[c$id$orig_h] = msg$auth_data;
}
```

... you have to have those payload types in clear text.  You don't have those payload types in this pcap.  You have some payloads here:

![Screen Shot 2022-02-09 at 11 59 43 AM](https://user-images.githubusercontent.com/5360855/153251374-91061f80-3671-4222-87f4-b35d193f183f.png)

... but not of type AUTH or EAP payload.  Later in the pcap there is the IKE_AUTH exchange type and you see some encrypted data here:

![Screen Shot 2022-02-09 at 12 00 18 PM](https://user-images.githubusercontent.com/5360855/153251492-ab6bb2ab-78c5-401d-94f2-1f334f7191d8.png)

I don't know if that encrypted data will have what you need, or not, and I doubt it can be decrypted easily to check.  So in short, the data you want is not in your pcap and may not be trivial to get.  There may be some other way to do this in ipsec, but those events won't fire unless an AUTH or EAP payload is seen.

**Comment by pagey101** [comment]
Thanks for your help, understood!
